import { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Air Max Pulse",
    brand: "Nike",
    price: 13999,
    originalPrice: 15999,
    images: ["/products/nike_air_max_pulse.png"],
    category: "men",
    type: "sneakers",
    colors: ["Black", "White", "Red"],
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.5,
    reviewCount: 234,
    description: "The Air Max Pulse draws inspiration from the iconic Air Max line, featuring a sleek design with visible Air cushioning for maximum comfort.",
    isNew: true,
    isTrending: true,
  },
  {
    id: "2",
    name: "Ultraboost Light",
    brand: "Adidas",
    price: 16999,
    images: ["/products/adidas_ultraboost_light.png"],
    category: "men",
    type: "running",
    colors: ["White", "Black", "Blue"],
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.7,
    reviewCount: 189,
    description: "Experience incredible energy return with the lightest Ultraboost ever. Featuring LIGHT BOOST midsole for a responsive ride.",
    isTrending: true,
  },
  {
    id: "3",
    name: "Classic Leather",
    brand: "Reebok",
    price: 7999,
    originalPrice: 9999,
    images: ["/products/reebok_classic_leather.png"],
    category: "women",
    type: "sneakers",
    colors: ["White", "Pink", "Beige"],
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.3,
    reviewCount: 145,
    description: "Timeless style meets modern comfort in this iconic silhouette. Soft leather upper with cushioned midsole.",
  },
  {
    id: "4",
    name: "Gel-Kayano 30",
    brand: "ASICS",
    price: 14999,
    images: ["/products/asics_gel_kayano_30.png"],
    category: "men",
    type: "running",
    colors: ["Blue", "Black", "Green"],
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.8,
    reviewCount: 312,
    description: "The 30th edition of the legendary stability running shoe. Features 4D GUIDANCE SYSTEM for enhanced support.",
    isNew: true,
  },
  {
    id: "5",
    name: "Chuck 70 High Top",
    brand: "Converse",
    price: 6999,
    images: ["/products/converse_chuck_70.png"],
    category: "unisex",
    type: "casual",
    colors: ["Black", "White", "Red", "Navy"],
    sizes: [5, 6, 7, 8, 9, 10, 11, 12],
    rating: 4.4,
    reviewCount: 567,
    description: "The Chuck 70 updates the archival Chuck Taylor with premium materials and improved cushioning.",
    isTrending: true,
  },
  {
    id: "6",
    name: "Suede XL",
    brand: "Puma",
    price: 5999,
    originalPrice: 7999,
    images: ["/products/puma_suede_xl.png"],
    category: "women",
    type: "sneakers",
    colors: ["Pink", "Green", "Black"],
    sizes: [5, 6, 7, 8, 9],
    rating: 4.2,
    reviewCount: 98,
    description: "A bold, upsized take on the iconic PUMA Suede. Features premium suede upper and thick rubber outsole.",
  },
  {
    id: "7",
    name: "574 Core",
    brand: "New Balance",
    price: 8999,
    images: ["/products/new_balance_574.png"],
    category: "men",
    type: "sneakers",
    colors: ["Grey", "Navy", "Black"],
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.6,
    reviewCount: 423,
    description: "The iconic 574 silhouette with ENCAP midsole technology for superior comfort and durability.",
    isTrending: true,
  },
  {
    id: "8",
    name: "Litewave Trail",
    brand: "The North Face",
    price: 11999,
    images: ["/products/tnf_litewave_trail.png"],
    category: "men",
    type: "boots",
    colors: ["Brown", "Black", "Green"],
    sizes: [8, 9, 10, 11, 12],
    rating: 4.5,
    reviewCount: 156,
    description: "Lightweight trail shoes built for speed on rugged terrain. Features OrthoLite footbed for all-day comfort.",
  },
  {
    id: "9",
    name: "Cloudmonster 2",
    brand: "On",
    price: 15999,
    originalPrice: 18999,
    images: ["/products/on_cloudmonster_2.png"],
    category: "women",
    type: "running",
    colors: ["White", "Black", "Coral"],
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.7,
    reviewCount: 278,
    description: "Maximum cushioning meets bold design. CloudTec Phase technology delivers a soft landing and explosive takeoff.",
    isNew: true,
  },
  {
    id: "10",
    name: "Old Skool",
    brand: "Vans",
    price: 4999,
    images: ["/products/vans_old_skool.png"],
    category: "kids",
    type: "casual",
    colors: ["Black", "White", "Checkerboard"],
    sizes: [3, 4, 5, 6],
    rating: 4.5,
    reviewCount: 890,
    description: "The Old Skool is a classic Vans silhouette featuring the iconic side stripe, durable canvas and suede uppers.",
  },
  {
    id: "11",
    name: "Forum Low",
    brand: "Adidas",
    price: 9999,
    originalPrice: 11999,
    images: ["/products/adidas_forum_low.png"],
    category: "women",
    type: "sneakers",
    colors: ["White", "Purple", "Green"],
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.3,
    reviewCount: 201,
    description: "Originally a basketball shoe from the '80s, the Forum Low brings retro style with modern comfort.",
  },
  {
    id: "12",
    name: "Clifton 9",
    brand: "HOKA",
    price: 12999,
    images: ["/products/hoka_clifton_9.png"],
    category: "men",
    type: "running",
    colors: ["Black", "White", "Blue"],
    sizes: [8, 9, 10, 11, 12, 13],
    rating: 4.8,
    reviewCount: 445,
    description: "The Clifton 9 delivers a plush yet responsive ride with lighter-weight, resilient foam and a streamlined design.",
    isNew: true,
    isTrending: true,
  },
];

export const brands = ["Nike", "Adidas", "Reebok", "ASICS", "Converse", "Puma", "New Balance", "The North Face", "On", "Vans", "HOKA"];

export const categories = [
  { name: "Performance Runners", slug: "men", count: 156, image: "/placeholder.svg" },
  { name: "Urban Lifestyle", slug: "women", count: 142, image: "/placeholder.svg" },
  { name: "Outdoor & Trail", slug: "men", count: 87, image: "/placeholder.svg" },
  { name: "Casual Classics", slug: "unisex", count: 234, image: "/placeholder.svg" },
];

export const shoeTypes = ["sneakers", "running", "casual", "boots", "heels", "sandals", "formal"];

export const ugcPhotos = [
  { id: "1", image: "/placeholder.svg", username: "@alex_sneaks" },
  { id: "2", image: "/placeholder.svg", username: "@jess_walks" },
  { id: "3", image: "/placeholder.svg", username: "@urban_style" },
];
